[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@ERC721A/contracts=lib/ERC721A/contracts"
]
via_ir = false
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.solx]
solc_version = "/Users/carlosgutierrez/.local/bin/solx"